# Generated by Django 4.2 on 2024-04-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecNotes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseCode',
            field=models.IntegerField(),
        ),
    ]
