# Generated by Django 4.2 on 2024-04-07 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecNotes_app', '0002_alter_course_coursecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseName',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('courses', models.ManyToManyField(to='lecNotes_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='LectureNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursePrefix', models.CharField(max_length=200)),
                ('courseCode', models.IntegerField()),
                ('courseName', models.CharField(blank=True, max_length=200)),
                ('lectureDate', models.DateField()),
                ('lectureNum', models.IntegerField()),
                ('notesAuthor', models.CharField(blank=True, max_length=200)),
                ('courseLecturer', models.CharField(max_length=200)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lecNotes_app.course')),
            ],
        ),
    ]
