# Generated by Django 4.2 on 2024-04-07 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecNotes_app', '0004_course_courseprefixandcode_course_courseprogram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseLecturer',
        ),
    ]
