# Generated by Django 4.2 on 2024-04-07 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecNotes_app', '0005_remove_course_courselecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturenotes',
            name='lecturer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lecNotes_app.lecturer'),
        ),
    ]
