# Generated by Django 4.2 on 2024-04-07 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecNotes_app', '0006_lecturenotes_lecturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturenotes',
            name='courseLecturer',
        ),
    ]
