# Generated by Django 4.2 on 2024-04-08 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecNotes_app', '0007_remove_lecturenotes_courselecturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='courseProgram',
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lecNotes_app.program'),
        ),
    ]
