# Generated by Django 4.2 on 2024-04-27 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lecNotes_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecNotes_app', '0011_alter_lecturenotes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturenotes',
            name='user',
            field=models.ForeignKey(default=lecNotes_app.models.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
